version: '3.4'

services:
  nginx:
    image: nginx:1.19-alpine
    container_name: kuzzle_nginx
    depends_on:
      - kuzzle
    ports:
      - '7512:7512'
    volumes:
      - ./docker/nginx-dev:/etc/nginx/conf.d

  kuzzle:
    image: kuzzleio/core-dev:2
    command: sh -c 'chmod 755 /run-dev.sh && /run-dev.sh && kuzzle start'
    container_name: kuzzle_container
    ports:
      - '17510:7512' # Kuzzle API port
      - '1883:1883' # Kuzzle MQTT port
      - '9229:9229' # Debug port
    volumes:
      - '.:/var/app'
      - './docker/scripts/run-dev.sh:/run-dev.sh'
      - './docker/fixtures:/fixtures'
    cap_add:
      - SYS_PTRACE
    ulimits:
      nofile: 65536
    sysctls:
      - net.core.somaxconn=8192
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      - kuzzle_services__storageEngine__client__node=http://elasticsearch:9200
      - kuzzle_services__storageEngine__commonMapping__dynamic=true
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_server__protocols__mqtt__enabled=true
      - kuzzle_server__protocols__mqtt__developmentMode=false
      - kuzzle_limits__loginsPerSecond=50
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG:-kuzzle:*,-kuzzle:network:protocols:websocket,-kuzzle:events}
      # - DEBUG=${DEBUG:-none}
      - DEBUG_DEPTH=${DEBUG_DEPTH:-0}
      - DEBUG_MAX_ARRAY_LENGTH=${DEBUG_MAX_ARRAY:-100}
      - DEBUG_EXPAND=${DEBUG_EXPAND:-off}
      - DEBUG_SHOW_HIDDEN={$DEBUG_SHOW_HIDDEN:-on}
      - DEBUG_COLORS=${DEBUG_COLORS:-on}
      - KUZZLE_VAULT_KEY=${KUZZLE_VAULT_KEY:-secret-password}
      - KUZZLE_SECRETS_FILE=${KUZZLE_SECRETS_FILE:-/var/app/features/fixtures/secrets.enc.json}
      # Variables used by the development scripts
      - NODE_12_VERSION=12.20.0
      - NODE_14_VERSION=14.17.0
      - WITHOUT_KUZZLE # Run only Elasticsearch and Redis
      - REBUILD # Force a rebuild of npm modules

  redis:
    image: redis:6
    container_name: kuzzle_redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 30

  elasticsearch:
    image: kuzzleio/elasticsearch:7
    container_name: kuzzle_elasticsearch
    ports:
      - '9200:9200'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9200']
      interval: 2s
      timeout: 2s
      retries: 10
    ulimits:
      nofile: 65536
